### ISSUE TITLE
alpha_max y alpha_min estan cruzados en Ejemplo diseño Chebyshev.ipynb

### ISSUE THREAD

**Issue by ivanpauno** [agalbachicar/tc2#29]
**Describa el problema**

Mismo que https://github.com/agalbachicar/tc2/pull/27.
Aplica a https://github.com/agalbachicar/tc2/blob/master/notebooks/Ejemplo%20dise%C3%B1o%20Chebyshev.ipynb.

**Comment by agalbachicar** [comment]
Solucionado via #27

**Comment by ivanpauno** [comment]
#27 soluciono el problema para el ejemplo maxima planicidad.
Esta issue es para trackear la misma correccion en el ejemplo Chebyshev.

**Comment by agalbachicar** [comment]
Ahora si! #31 la soluciona.
